/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ace.prms.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the plantation service. Represents a row in the &quot;prms_plantation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ace.prms.sb.model.impl.plantationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ace.prms.sb.model.impl.plantationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see plantation
 * @generated
 */
@ProviderType
public interface plantationModel
	extends BaseModel<plantation>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a plantation model instance should use the {@link plantation} interface instead.
	 */

	/**
	 * Returns the primary key of this plantation.
	 *
	 * @return the primary key of this plantation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this plantation.
	 *
	 * @param primaryKey the primary key of this plantation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this plantation.
	 *
	 * @return the uuid of this plantation
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this plantation.
	 *
	 * @param uuid the uuid of this plantation
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the plant ID of this plantation.
	 *
	 * @return the plant ID of this plantation
	 */
	public long getPlantId();

	/**
	 * Sets the plant ID of this plantation.
	 *
	 * @param plantId the plant ID of this plantation
	 */
	public void setPlantId(long plantId);

	/**
	 * Returns the group ID of this plantation.
	 *
	 * @return the group ID of this plantation
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this plantation.
	 *
	 * @param groupId the group ID of this plantation
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this plantation.
	 *
	 * @return the company ID of this plantation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this plantation.
	 *
	 * @param companyId the company ID of this plantation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this plantation.
	 *
	 * @return the user ID of this plantation
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this plantation.
	 *
	 * @param userId the user ID of this plantation
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this plantation.
	 *
	 * @return the user uuid of this plantation
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this plantation.
	 *
	 * @param userUuid the user uuid of this plantation
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this plantation.
	 *
	 * @return the user name of this plantation
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this plantation.
	 *
	 * @param userName the user name of this plantation
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this plantation.
	 *
	 * @return the create date of this plantation
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this plantation.
	 *
	 * @param createDate the create date of this plantation
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this plantation.
	 *
	 * @return the modified date of this plantation
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this plantation.
	 *
	 * @param modifiedDate the modified date of this plantation
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the plant type of this plantation.
	 *
	 * @return the plant type of this plantation
	 */
	@AutoEscape
	public String getPlantType();

	/**
	 * Sets the plant type of this plantation.
	 *
	 * @param plantType the plant type of this plantation
	 */
	public void setPlantType(String plantType);

	/**
	 * Returns the name of this plantation.
	 *
	 * @return the name of this plantation
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this plantation.
	 *
	 * @param name the name of this plantation
	 */
	public void setName(String name);

	/**
	 * Returns the origin of this plantation.
	 *
	 * @return the origin of this plantation
	 */
	@AutoEscape
	public String getOrigin();

	/**
	 * Sets the origin of this plantation.
	 *
	 * @param origin the origin of this plantation
	 */
	public void setOrigin(String origin);

	/**
	 * Returns the yield measure of this plantation.
	 *
	 * @return the yield measure of this plantation
	 */
	public int getYieldMeasure();

	/**
	 * Sets the yield measure of this plantation.
	 *
	 * @param yieldMeasure the yield measure of this plantation
	 */
	public void setYieldMeasure(int yieldMeasure);

	/**
	 * Returns the life span of this plantation.
	 *
	 * @return the life span of this plantation
	 */
	public int getLifeSpan();

	/**
	 * Sets the life span of this plantation.
	 *
	 * @param lifeSpan the life span of this plantation
	 */
	public void setLifeSpan(int lifeSpan);

	/**
	 * Returns the breed of this plantation.
	 *
	 * @return the breed of this plantation
	 */
	@AutoEscape
	public String getBreed();

	/**
	 * Sets the breed of this plantation.
	 *
	 * @param breed the breed of this plantation
	 */
	public void setBreed(String breed);

}